"""Report Generator - Phase 10."""

from typing import Dict, List, Any
import json
from datetime import datetime
from app.core.logger import logger
from app.core.security import audit_log

class ReportService:
    @staticmethod
    async def generate_markdown_report(workflow_result: Dict, query: str) -> str:
        """Tạo báo cáo Markdown đẹp."""
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

        md = f"""# Báo cáo PenTest - GraphRAG

**Thời gian**: {now}  
**Query**: {query}

## 1. Tóm tắt
- Số entities được extract: {len(workflow_result.get('graph_context', {}).get('entities', []))}
- Số relations: {len(workflow_result.get('graph_context', {}).get('relations', []))}
- Số kết quả retrieval: {len(workflow_result.get('retrieval_results', []))}
- Trạng thái workflow: **{workflow_result.get('current_step', 'completed')}**

## 2. Key Findings
"""

        # Thêm findings từ graph
        for finding in workflow_result.get('tool_results', []):
            md += f"- **{finding.get('cve_id', 'N/A')}**: {finding.get('description', '')[:200]}...\n"

        md += "\n## 3. Khuyến nghị\n"
        md += "- Kiểm tra target trong môi trường lab\n"
        md += "- Cập nhật patch cho các CVE có `is_exploitable: true`\n"
        md += "- Chạy scan định kỳ với Nuclei\n"

        md += f"\n---\n*Generated by GraphRAG Pentest Platform - {now}*"
        return md

    @staticmethod
    async def generate_json_report(workflow_result: Dict, query: str) -> Dict:
        """Tạo báo cáo JSON đầy đủ."""
        return {
            "report_id": f"report-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}",
            "generated_at": datetime.utcnow().isoformat(),
            "query": query,
            "workflow_summary": workflow_result,
            "markdown": await ReportService.generate_markdown_report(workflow_result, query),
            "version": "1.0"
        }