server.document-root = "/var/www/localhost/htdocs"
server.port          = 80
# Override version string in HTTP Server header
server.tag           = "lighttpd/1.4.55"
server.errorlog      = "/var/log/lighttpd/error.log"

mimetype.assign = (
    ".html" => "text/html",
    ".txt"  => "text/plain",
    ".css"  => "text/css",
    ".js"   => "application/javascript"
)

index-file.names = ("index.html")
