[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:dropbear]
# -F = foreground, -p 22 = listen port
command=/usr/sbin/dropbear -F -p 22
autostart=true
autorestart=true

[program:lighttpd]
command=/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
autostart=true
autorestart=true
