# ServerIdent overrides the 220 banner — nmap sees "ProFTPD 1.3.5"
ServerIdent on "ProFTPD 1.3.5 Server (ProFTPD Default Installation)"
ServerType standalone
DefaultServer on
Port 21
Umask 022
MaxInstances 30
User nobody
Group nogroup
AllowOverwrite on
UseReverseDNS off
IdentLookups off
PassivePorts 60000 65534

<Directory />
    AllowOverwrite on
</Directory>
